# fly.toml app configuration file generated for resort-ai-chatbot on 2025-07-02T08:46:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'resort-ai-chatbot'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
